
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: smschatbox@gmail.com
    password: vijuxmsugpzdbixy
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:templates/
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: authentication-service
  flyway:
    locations:
      - classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 708657316965-9q83lt1cspvgvusqbqp19ir3s0jut05d.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  exclude:
    url:
      path: api-config/exclude.mapping.json
  pem-key:
    private: keys/private_key.pem
    public: keys/public_key.pem

server:
  port: 8085
  servlet:
    context-path: /security

rabbitmq:
  mail:
    queue: mail-queue
    exchange: mail-exchange
    routingkey: user-key


