
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: authentication-service
  flyway:
    locations:
      - classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 708657316965-9q83lt1cspvgvusqbqp19ir3s0jut05d.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

server:
  port: 8085
  servlet:
    context-path: /security



