
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: authentication-service
  flyway:
    locations:
      - classpath:/db/migration
  config:
    location: classpath:/properties

server:
  port: 8085
  servlet:
    context-path: /security


jwt:
  security-key: secret-key

